users.bob.active=false
users.bob.name=Bob
users.alice.active=true
users.alice.roles.__values__.1=user
users.alice.name=Alice
users.bob.age=25
users.alice.roles.__values__.0=admin
users.alice.roles.__type__=ListSection
users.alice.age=30
