permissions.1=WRITE
permissions.0=READ
permissions.__values__.2=EXECUTE
metadata.version=1
metadata.valid=true
permissions.__values__.0=READ
permissions.__values__.1=WRITE
metadata.__type__=MapSection
permissions.__type__=ListSection
metadata.created=today
permissions.2=EXECUTE
