package de.happybavarian07.coolstufflib.jpa.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * <p>Specifies the strategy for automatically generating primary key values.</p>
 *
 * <p>This annotation is applied to fields annotated with {@link Id} to define how the
 * persistence layer should generate unique identifier values for new entity instances.
 * Without this annotation, you must manually set the ID value before persisting entities.</p>
 *
 * <h3>Generation Strategies:</h3>
 * <p>The available strategies are defined in {@link GenerationType} enum. Each strategy
 * has different characteristics regarding performance, portability, and ID sequence behavior.</p>
 *
 * <pre>{@code
 * @Entity(name = "Order")
 * public class Order {
 *     @Id
 *     @GeneratedValue(strategy = GenerationType.IDENTITY)
 *     private Long id;
 *     
 *     private String customerName;
 *     private double totalAmount;
 * }
 * }</pre>
 *
 * <h3>When to Use:</h3>
 * <ul>
 *   <li>New entities without an ID - the strategy generates one automatically</li>
 *   <li>ID is typically generated at PERSIST time (before INSERT statement)</li>
 *   <li>Generated IDs should not be manually set by application code</li>
 * </ul>
 *
 * <h3>Strategy Comparison:</h3>
 * See {@link GenerationType} for detailed description of each strategy and recommendations.</p>
 *
 * @param strategy The primary key generation strategy to use. Default is AUTO,
 *                 which lets the persistence provider choose an appropriate strategy.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface GeneratedValue {
    /**
     * <p>Specifies the algorithm used for generating primary key values.</p>
     *
     * <p>The {@link GenerationType} enum defines four strategies:</p>
     *
     * <h4>{@link GenerationType#AUTO}</h4>
     * <p>The persistence provider chooses an appropriate generation strategy automatically.
     * This is the default and recommended for most cases where you don't have specific
     * requirements.</p>
     *
     * <pre>{@code
     * @Id
     * @GeneratedValue(strategy = GenerationType.AUTO)
     * private Long id;  // Provider decides the best approach
     * }</pre>
     *
     * <h4>{@link GenerationType#IDENTITY}</h4>
     * <p>Uses database identity columns for ID generation. The database automatically
     * generates a unique value (typically auto-increment in MySQL/MariaDB, IDENTITY
     * in SQL Server) when inserting new rows.</p>
     *
     * <pre>{@code
     * @Id
     * @GeneratedValue(strategy = GenerationType.IDENTITY)
     * private Long id;  // Database auto-increment column
     *
     * Order order = new Order();
     * order.setCustomerName("John");
     * entityManager.persist(order);
     * System.out.println(order.getId());  // ID generated by database after persist
     * }</pre>
     *
     * <ul>
     *   <li><strong>Pros:</strong> Simple setup, no additional table needed, efficient</li>
     *   <li><strong>Cons:</strong> Database-specific (not portable), ID only known after INSERT</li>
     *   <li><strong>Supported by:</strong> MySQL, MariaDB, PostgreSQL (SERIAL), SQL Server</li>
     * </ul>
     *
     * <h4>{@link GenerationType#SEQUENCE}</h4>
     * <p>Uses a database sequence object to generate IDs. A sequence is a special database
     * object that generates unique numeric values on demand.</p>
     *
     * <pre>{@code
     * @Id
     * @GeneratedValue(strategy = GenerationType.SEQUENCE,
     *                 generator = "order_sequence")
     * private Long id;
     *
     * Order order = new Order();  // ID can be generated before persist
     * entityManager.persist(order);
     * System.out.println(order.getId());  // ID already known, no extra query needed
     * }</pre>
     *
     * <ul>
     *   <li><strong>Pros:</strong> IDs known before INSERT (allows pre-insert operations),
     *       highly portable across databases that support sequences</li>
     *   <li><strong>Cons:</strong> Requires sequence object creation; not supported by MySQL
     *       (use IDENTITY or TABLE instead)</li>
     *   <li><strong>Supported by:</strong> PostgreSQL, Oracle, DB2, H2</li>
     * </ul>
     *
     * <h4>{@link GenerationType#TABLE}</h4>
     * <p>Uses a dedicated table to track ID generation. A special table stores the current
     * sequence value and increments it for each new ID.</p>
     *
     * <pre>{@code
     * @Id
     * @GeneratedValue(strategy = GenerationType.TABLE)
     * private Long id;
     *
     * // Uses a table like:
     * // CREATE TABLE entity_generator (
     * //     pk_name VARCHAR(255) PRIMARY KEY,
     * //     pk_value BIGINT
     * // );
     * }</pre>
     *
     * <ul>
     *   <li><strong>Pros:</strong> Maximum portability (works on all databases), no special
     *       database objects needed, IDs known before INSERT</li>
     *   <li><strong>Cons:</strong> Requires additional SELECT/UPDATE per entity insert,
     *       potential concurrency issues without proper locking</li>
     * </ul>
     *
     * <h3>Recommendations by Use Case:</h3>
     *
     * | Scenario | Recommended Strategy |
     * \|----------|----------------------|
     * | MySQL/MariaDB database | IDENTITY |
     * | PostgreSQL, Oracle | SEQUENCE |
     * | Maximum portability needed | TABLE |
     * | Database choice undecided | AUTO |
     *
     * <h3>Important Considerations:</h3>
     * <ul>
     *   <li><strong>ID visibility timing</strong>: IDENTITY generates IDs after INSERT;
     *       SEQUENCE and TABLE generate IDs before INSERT</li>
     *   <li><strong>Performance</strong>: SEQUENCE is typically fastest, then IDENTITY,
     *       AUTO depends on provider; TABLE has overhead from extra table access</li>
     *   <li><strong>Distributed systems</strong>: Consider using a unique generator name
     *       per entity type to avoid collisions in clustered environments</li>
     * </ul>
     *
     * @return The generation strategy to use. Default is AUTO.
     */
    GenerationType strategy() default GenerationType.AUTO;
}
