package de.happybavarian07.coolstufflib.jpa.annotations;

/**
 * <p>Defines the available strategies for automatically generating primary key values.</p>
 *
 * <p>This enum is used with {@link GeneratedValue} to specify how unique identifiers
 * should be generated for entity instances. The choice of strategy affects performance,
 * portability, and when the ID becomes known (before or after persist).</p>
 *
 * <h3>Strategy Selection Guide:</h3>
 *
 * | Strategy | Best For | Pros | Cons |
 * \|----------|------------|------\|-----|
     * | AUTO | General use, undecided database | Provider picks optimal strategy | Less predictable |
     * | IDENTITY | MySQL, MariaDB, SQL Server | Simple, no extra setup | ID known only after INSERT |
     * | SEQUENCE | PostgreSQL, Oracle, DB2 | Fast, ID known before INSERT | Not supported by MySQL |
     * | TABLE | Maximum portability needed | Works on all databases | Slower, requires extra table |
 *
 * <h3>Common Configuration Patterns:</h3>
 *
 * <pre>{@code
 * // MySQL database - use IDENTITY for auto-increment
 * @Entity(name = "User")
 * public class User {
 *     @Id
 *     @GeneratedValue(strategy = GenerationType.IDENTITY)
 *     private Long id;
 * }
 *
 * // PostgreSQL or Oracle - use SEQUENCE for best performance
 * @Entity(name = "Product")
 * public class Product {
 *     @Id
 *     @GeneratedValue(strategy = GenerationType.SEQUENCE,
 *                     generator = "product_seq")
 *     private Long id;
 * }
 *
 * // Database agnostic code - let provider decide
 * @Entity(name = "Order")
 * public class Order {
 *     @Id
 *     @GeneratedValue(strategy = GenerationType.AUTO)
 *     private Long id;  // Provider chooses based on dialect
 * }
 * }</pre>
 *
 * <h3>Key Differences:</h3>
 * <ul>
 *   <li><strong>ID Visibility</strong>: SEQUENCE and TABLE generate IDs before INSERT;
     *       IDENTITY generates after INSERT; AUTO depends on provider choice</li>
 *   <li><strong>Performance</strong>: SEQUENCE &gt; IDENTITY &gt; AUTO &gt; TABLE (generally)</li>
 *   <li><strong>Portability</strong>: TABLE works everywhere; others are database-specific</li>
 * </ul>
 */
public enum GenerationType {
    /**
     * <p>Let the persistence provider automatically choose an appropriate generation strategy.</p>
     *
     * <p>When using AUTO, the JPA implementation examines the target database and selects
     * the most suitable strategy. For example:</p>
     *
     * <ul>
     *   <li><strong>MySQL/MariaDB</strong>: Typically chooses IDENTITY (auto-increment)</li>
     *   <li><strong>PostgreSQL</strong>: May choose SEQUENCE or IDENTITY (SERIAL column)</li>
     *   <li><strong>Oracle</strong>: Chooses SEQUENCE</li>
     *   <li><strong>SQL Server</strong>: Chooses IDENTITY</li>
     * </ul>
     *
     * <pre>{@code
     * @Entity(name = "Customer")
     * public class Customer {
     *     @Id
     *     @GeneratedValue(strategy = GenerationType.AUTO)
     *     private Long id;  // Provider decides based on configured database
     * }
     * }</pre>
     *
     * <p><strong>When to use:</strong></p>
     * <ul>
     *   <li>New projects where you haven't decided on specific ID requirements</li>
     *   <li>Applications that may run against different database types</li>
     *   <li>Rapid prototyping and development</li>
     * </ul>
     *
     * <p><strong>Caveats:</strong></p>
     * <ul>
     *   <li>The actual strategy used depends on the JPA provider's implementation</li>
     *   <li>Behavior may differ between providers (Hibernate, EclipseLink, etc.)</li>
     *   <li>ID visibility timing uncertain until you know which strategy was chosen</li>
     * </ul>
     *
     * For production systems with specific requirements, explicitly specifying IDENTITY,
     * SEQUENCE, or TABLE is recommended over AUTO.
     */
    AUTO,

    /**
     * <p>Uses database identity columns for automatic ID generation.</p>
     *
     * <p>This strategy relies on the database's built-in auto-increment functionality:
     * MySQL/MariaDB AUTO_INCREMENT, PostgreSQL SERIAL, SQL Server IDENTITY. The database
     * automatically generates a unique numeric value each time a new row is inserted.
     *</p>
     *
     * <pre>{@code
     * @Entity(name = "Employee")
     * public class Employee {
     *     @Id
     *     @GeneratedValue(strategy = GenerationType.IDENTITY)
     *     private Long id;  // Database auto-increment column
     * }
     *
     * // Usage:
     * Employee emp = new Employee();
     * emp.setName("John Doe");
     * entityManager.persist(emp);
     *
     * System.out.println(emp.getId());  // ID now known (generated by database)
     * }</pre>
     *
     * <h3>Characteristics:</h3>
     * <ul>
     *   <li><strong>ID Generation Time</strong>: After INSERT - the ID is only known after
     *       the entity is persisted to the database</li>
     *   <li><strong>Database Support</strong>: MySQL, MariaDB, PostgreSQL (SERIAL), SQL Server,
     *       H2; NOT supported by Oracle, DB2</li>
     * </ul>
     *
     * <h3>Pros:</h3>
     * <ul>
     *   <li>No additional database objects needed (no sequence or table)</li>
     *   <li>Simplicity - just define the ID column as auto-increment</li>
     *   <li>Good performance for single-insert scenarios</li>
     *   <li>Natively supported by most common databases</li>
     * </ul>
     *
     * <h3>Cons:</h3>
     * <ul>
     *   <li>ID only available after INSERT - cannot reference the ID before persisting
     *       (problematic for one-to-many relationships where child needs parent's ID)</li>
     *   <li>Database-specific feature - reduces portability</li>
     *   <li>Distributed systems may have issues with auto-increment sequences</li>
     * </ul>
     *
     * <p><strong>Recommendation:</strong> Use IDENTITY for MySQL/MariaDB databases where
     * you don't need the ID before persist, or when simplicity is prioritized over portability.</p>
     */
    IDENTITY,

    /**
     * <p>Uses database sequences to generate unique IDs.</p>
     *
     * <p>A sequence is a special database object that maintains a counter and generates
     * unique numeric values on request. Each call to NEXTVAL retrieves the next value
     * in the sequence, which can then be used as the entity's primary key.</p>
     *
     * <pre>{@code
     * @Entity(name = "Invoice")
     * public class Invoice {
     *     @Id
     *     @GeneratedValue(strategy = GenerationType.SEQUENCE,
     *                     generator = "invoice_seq")  // Named sequence
     *     private Long id;
     *
     *     // Can also specify sequence parameters:
     *     // @SequenceGenerator(name = "invoice_seq",
     *     //                     sequenceName = "invoice_id_seq",
     *     //                     initialValue = 1000,
     *     //                     allocationSize = 50)
     * }
     *
     * // Usage:
     * Invoice inv = new Invoice();
     * entityManager.persist(inv);
     * System.out.println(inv.getId());  // ID known immediately - generated by sequence
     * }</pre>
     *
     * <h3>Characteristics:</h3>
     * <ul>
     *   <li><strong>ID Generation Time</strong>: Before INSERT - the ID is generated and
     *       set on the entity before it's persisted to the database</li>
     *   <li><strong>Database Support</strong>: PostgreSQL, Oracle, DB2, H2; NOT supported by MySQL
     *       (use IDENTITY or TABLE instead)</li>
     * </ul>
     *
     * <h3>Pros:</h3>
     * <ul>
     *   <li>ID known before INSERT - can establish relationships in single transaction</li>
     *   <li>High performance - sequence access is typically faster than table reads</li>
     *   <li>Configurable parameters: initial value, increment size, cache size</li>
     *   <li>Better suited for distributed systems and batch inserts</li>
     * </ul>
     *
     * <h3>Cons:</h3>
     * <ul>
     *   <li>Requires sequence object to be created in database (setup overhead)</li>
     *   <li>Not supported by all databases (notably MySQL)</li>
     * </ul>
     *
     * <p><strong>Recommendation:</strong> Use SEQUENCE for PostgreSQL, Oracle, or DB2
     * databases when you need IDs before persist or want maximum performance.</p>
     */
    SEQUENCE,

    /**
     * <p>Uses a dedicated database table to track and generate primary key values.</p>
     *
     * <p>This strategy maintains ID generation state in a regular database table rather
     * than using database-specific features like sequences or identity columns. A special
     * row stores the current value for each entity type, which is incremented atomically
     * for each new ID generated.</p>
     *
     * <pre>{@code
     * // Typical structure of the generator table:
     * // CREATE TABLE entity_generator (
     * //     pk_name VARCHAR(255) PRIMARY KEY,
     * //     next_val BIGINT NOT NULL
     * // );
     *
     * @Entity(name = "Session")
     * public class Session {
     *     @Id
     *     @GeneratedValue(strategy = GenerationType.TABLE)
     *     private Long id;  // ID generated from entity_generator table
     * }
     * }</pre>
     *
     * <h3>Characteristics:</h3>
     * <ul>
     *   <li><strong>ID Generation Time</strong>: Before INSERT - similar to SEQUENCE,
     *       the ID is generated and set before persisting the entity</li>
     *   <li><strong>Database Support</strong>: ALL databases - maximum portability since
     *       it only requires basic table operations</li>
     * </ul>
     *
     * <h3>Pros:</h3>
     * <ul>
     *   <li>Maximum portability - works on any database without special setup</li>
     *   <li>ID known before INSERT - allows relationship establishment in one transaction</li>
     *   <li>No database-specific objects needed (no sequences, auto-increment)</li>
     * </ul>
     *
     * <h3>Cons:</h3>
     * <ul>
     *   <li>Performance overhead - requires SELECT and UPDATE on generator table per entity</li>
     *   <li>Potential concurrency issues if proper locking (SELECT FOR UPDATE) not used</li>
     *   <li>Additional database round-trip for each new entity insert</li>
     * </ul>
     *
     * <p><strong>Recommendation:</strong> Use TABLE when you need maximum portability across
     * different database types and don't have specific performance requirements. Often a good
     * choice for applications that may switch databases or run in heterogeneous environments.</p>
     */
    TABLE
}
